### ISSUE TITLE
DropDown

### ISSUE THREAD

**Issue by xBisharp** [Company-Social-Events/mern-frontend#7]
The name selected in the DropDown  is not shown
Not sure if the DropDown.tsx file is the problem or ChipPicker.tsx

**Comment by gandolh** [comment]
There is a problem in the UI framework we use. He renders the <Select> element as buttons so any react tricks to manage states of select can easily mess with its internal work. It is fixed for the moment because i switched how it was implemented in a simpler version, using only a static array of strings and a map that renders <Option> elements. That will do the work until the framework is updated to a more stable version.
